// Generated by dojo-bindgen on Sat, 24 Feb 2024 21:46:30 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;


// Model definition for `tale_weaver::models::avatar::Avatar` model
public class Avatar : ModelInstance {
    [ModelField("id")]
    public uint id;

    [ModelField("player")]
    public FieldElement player;

    [ModelField("name")]
    public FieldElement name;

    [ModelField("alias")]
    public FieldElement alias;

    [ModelField("description")]
    public FieldElement description;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}
        