// Generated by dojo-bindgen on Sat, 24 Feb 2024 21:46:30 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;

// Type definition for `tale_weaver::models::seed::WorldModeID` enum
public enum WorldModeID {
    None,
    Adventure,
    Creative,
    Survival,
}

// Type definition for `tale_weaver::models::seed::WorldThemeID` enum
public enum WorldThemeID {
    None,
    Anime,
    PixelArt,
    Scifi,
    Fantasy,
    Cartoon,
    Realistic,
    Kids,
}


// Model definition for `tale_weaver::models::seed::Seed` model
public class Seed : ModelInstance {
    [ModelField("id")]
    public uint id;

    [ModelField("creator")]
    public FieldElement creator;

    [ModelField("avatar_id")]
    public uint avatar_id;

    [ModelField("title")]
    public FieldElement title;

    [ModelField("description")]
    public FieldElement description;

    [ModelField("openai_id")]
    public FieldElement openai_id;

    [ModelField("world_theme_id")]
    public WorldThemeID world_theme_id;

    [ModelField("world_mode_id")]
    public WorldModeID world_mode_id;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}
        